server:
  port: 8181
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shoppingcloud_payment?createDatabaseIfNotExist=true
    username: root
    password: test@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL55Dialect
  application:
    name: payment


